etcdEndpoint: "etcd.default.svc.cluster.local"
websocketHost: "websocket.k8s.likens.us"
dashboardHost: "dashboard.k8s.likens.us"
apiHost: "api.k8s.likens.us"
namespace: "sensu"
replicaCount: 1
image:
  repository: "sensu/sensu"
  tag: "latest"
etcd:
  replicaCount: 1
  auth:
    rbac:
      create: false
    token:
      enabled: false
    peer:
      secureTransport: true
      useAutoTLS: true
