---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sensu
spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Values.websocketHost }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: sensu-go
            port:
              number: 8081
  - host: {{ .Values.apiHost }}
    http: 
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: sensu-go
            port:
              number: 8080

  - host: {{ .Values.DashboardHost }}
    http: 
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: sensu-go
            port:
              number: 3000

