---
apiVersion: v1
kind: Service
metadata:
  name: sensu-go
  labels:
spec:
  ports:
    - port: 8081
      targetPort: 8081
      protocol: TCP
      name: sensu-ws
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: sensu-api
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: sensu-dashboard
  selector:
    app: sensu
